/**
 * index.js: Main Cloudflare Worker handler.
 *
 * Routes:
 *   OPTIONS  *              → CORS preflight
 *   GET  /health            → Liveness check (returns { status: 'ok' })
 *   GET  /widget-config     → Public widget settings (name, welcome message, accent colour)
 *   POST /chat              → Main chat endpoint (guarded, calls LLM, returns reply + CTAs)
 *   *    /demo/<slug>/*     → Password-gated business demos (see demo/handlers.js)
 *
 * /chat guard order (each guard returns null on pass, string on fail):
 *   1. guardOrigin      : request must come from an allowedOrigins domain
 *   2. guardWidgetToken : X-Widget-Token header must match WIDGET_TOKEN secret
 *   3. guardRateLimit   : enforces rateLimitRpm per IP
 *   4. guardMessageSize : message must be a non-empty string under maxMessageLength
 *   5. guardSessionLength: history must not exceed maxSessionMessages
 *   6. guardInjection   : blocks prompt injection phrases
 *   7. guardTopic       : blocks messages on explicitly blocked topics (no allowlist;
 *                         topic scope is enforced by the system prompt so lead messages
 *                         phrased in the visitor's own words are never pre-rejected)
 */

import { getConfig } from './config.js';
import { buildSystemPrompt } from './prompt.js';
import {
  guardOrigin, guardWidgetToken, guardRateLimit,
  guardMessageSize, guardSessionLength, guardInjection,
  guardTopic, guardOutput,
} from './guards.js';
import { validateLead, guardSendRate, sendOwnerEmail } from './email.js';
import { handleDemoRequest } from './demo/handlers.js';
// Generated by scripts/demo-build.js from setup/demos/ (gitignored). Run
// `npm run dev` or the deploy script and it is created for you.
import DEMOS from './demo/bundle.generated.js';

// Tool offered to the model when leadCapture.enabled is true. The model collects
// the three fields in conversation, then calls this once it has all of them.
// Sending is done by the worker, never by the model: see handleLeadToolCall.
const LEAD_TOOL = {
  type: 'function',
  function: {
    name: 'send_message_to_owner',
    description:
      'Email the visitor\'s enquiry to the site owner. Only call this after you have read the ' +
      'enquiry back to the visitor and they have explicitly agreed to it being sent. You must ' +
      'also have at least one contact route and their reason for getting in touch, both given ' +
      'explicitly by the visitor in this conversation. Never invent or guess any field.',
    parameters: {
      type: 'object',
      properties: {
        name:     { type: 'string', description: "The visitor's name, if they gave one." },
        email:    { type: 'string', description: "The visitor's email address, exactly as they wrote it. Leave out if not given." },
        phone:    { type: 'string', description: "The visitor's phone number, exactly as they wrote it. Leave out if not given." },
        linkedin: { type: 'string', description: "The visitor's LinkedIn profile URL, exactly as they wrote it. Leave out if not given." },
        reason:   { type: 'string', description: 'Why the visitor wants to be contacted, in their own words.' },
        confirmed: {
          type: 'boolean',
          description:
            'True only if the visitor has just explicitly agreed to this being sent, after you ' +
            'read it back to them. Never set this true on your own judgement.',
        },
      },
      required: ['reason', 'confirmed'],
    },
  },
};

const LEAD_INTENT_KEYWORDS = [
  'hire', 'work with', 'work together', 'pricing', 'price', 'cost', 'rate',
  'book a call', 'get in touch', 'reach out', 'quote', 'available for',
  'interested in working', 'engage', 'start a project', 'consult',
  'how much', 'what do you charge',
  'contact', 'how can i reach', 'how to reach', 'reach you', 'your email',
  'email address', 'connect with you', 'how do i message', 'linkedin',
  'whatsapp', 'drop you', 'send you',
];

export default {
  async fetch(request, env) {
    try {
      return await handleRequest(request, env);
    } catch (err) {
      console.error('[worker] Unhandled error:', err);
      const config = getConfig(env);
      return buildResponse({ error: 'Internal server error.' }, 500, request, config);
    }
  },
};

async function handleRequest(request, env) {
  const config = getConfig(env);
  const url    = new URL(request.url);

  if (request.method === 'OPTIONS') {
    return buildResponse(null, 204, request, config);
  }

  if (url.pathname === '/health' && request.method === 'GET') {
    return buildResponse({ status: 'ok' }, 200, request, config);
  }

  // Returns public widget config (bot name, welcome message, accent, suggested questions).
  // Checked by origin: safe to call without a widget token.
  if (url.pathname === '/widget-config' && request.method === 'GET') {
    const originError = guardOrigin(request, config);
    if (originError) return buildResponse({ error: originError }, 403, request, config);
    return buildResponse({
      botName:            config.botName,
      welcomeMessage:     config.ui?.welcomeMessage ?? `Hi! I'm ${config.botName}. How can I help?`,
      accentColor:        config.ui?.accentColor ?? '#0055ff',
      suggestedQuestions: config.ui?.suggestedQuestions ?? [],
    }, 200, request, config);
  }

  if (url.pathname === '/chat' && request.method === 'POST') {
    return await handleChat(request, env, config);
  }

  // Private business demos: /demo/<slug>/auth | config | chat. See demo/handlers.js.
  if (url.pathname.startsWith('/demo/')) {
    return await handleDemoRequest(request, env, config, url, {
      bundle:    DEMOS,
      callModel: async (systemPrompt, history, message, env2, cfg) =>
        (await callLLM(systemPrompt, history, message, env2, cfg)).text,
      respond:   (body, status) => buildResponse(body, status, request, config),
    });
  }

  return buildResponse({ error: 'Not found.' }, 404, request, config);
}

async function handleChat(request, env, config) {
  const originError = guardOrigin(request, config);
  if (originError) return buildResponse({ error: originError }, 403, request, config);

  const tokenError = guardWidgetToken(request, env);
  if (tokenError) return buildResponse({ error: tokenError }, 401, request, config);

  const ip = request.headers.get('CF-Connecting-IP') ?? 'unknown';
  const rateLimitError = guardRateLimit(ip, config);
  if (rateLimitError) return buildResponse({ error: rateLimitError }, 429, request, config);

  let body;
  try {
    body = await request.json();
  } catch {
    return buildResponse({ error: 'Invalid JSON.' }, 400, request, config);
  }

  const { message, history = [] } = body;

  const sizeError    = guardMessageSize(message, config);
  if (sizeError) return buildResponse({ error: sizeError }, 400, request, config);

  const sessionError = guardSessionLength(history, config);
  if (sessionError) return buildResponse({ error: sessionError }, 400, request, config);

  const injectionError = guardInjection(message);
  if (injectionError) return buildResponse({ error: injectionError }, 400, request, config);

  const topicError = guardTopic(message, config);
  if (topicError) return buildResponse({ reply: topicError }, 200, request, config);

  let profileText = env.PROFILE_TEXT_1 ?? env.PROFILE_TEXT ?? '';
  for (let i = 2; i <= 10; i++) profileText += env[`PROFILE_TEXT_${i}`] ?? '';
  const systemPrompt = buildSystemPrompt(config, profileText);
  const trimmedHistory = trimHistory(history, config);

  let result;
  try {
    result = await callLLM(systemPrompt, trimmedHistory, message, env, config);
  } catch (err) {
    console.error('[worker] LLM call failed:', err);
    return buildResponse(
      { error: 'Could not reach the assistant. Please try again.' },
      502, request, config
    );
  }

  // When the model asked to pass a message on, the worker does the sending and
  // writes the confirmation itself, so the visitor is never told a message was
  // sent unless it actually was.
  let reply = result.toolCall
    ? await handleLeadToolCall(result.toolCall, message, ip, env, config)
    : result.text;

  reply = guardOutput(reply, config.ownerName);

  // Attach contact buttons when the visitor shows lead intent OR when the reply
  // itself points the visitor at a contact route. The second case matters: many
  // declines and fallbacks say "using the contact buttons below" regardless of
  // the visitor's wording, so without this the buttons would be referenced but
  // never rendered.
  const cta = (detectLeadIntent(message) || replyRefersToContact(reply, config.contactMethods))
    ? buildCTAs(config.contactMethods)
    : [];

  return buildResponse({ reply, ...(cta.length && { cta }) }, 200, request, config);
}

// Runs the send the model asked for and returns the exact words the visitor sees.
// Every failure path returns the same kind of plain redirect to the contact
// buttons: the visitor is never left believing a message went out when it did not.
// Words a visitor uses to say yes. Checked against the visitor's own message on
// the turn the send is attempted, so agreement is read from what they actually
// typed rather than taken on the model's word that they agreed.
const AGREEMENT_PATTERN =
  /\b(yes|yeah|yep|yup|sure|ok|okay|please do|go ahead|go for it|do it|send it|send that|sounds good|that works|correct|confirmed|perfect|great)\b/i;

// True when this visitor message reads as agreement to send. Deliberately errs
// towards no: a missed yes costs one extra question, a wrongly assumed yes
// sends mail the visitor never sanctioned.
function visitorAgreed(message) {
  return typeof message === 'string' && AGREEMENT_PATTERN.test(message);
}

async function handleLeadToolCall(toolCall, message, ip, env, config) {
  const owner    = config.ownerName ?? 'me';
  const failText = `I could not pass that on just now, sorry. You can reach ${owner} directly using the contact buttons below.`;

  let args;
  try {
    args = JSON.parse(toolCall.arguments ?? '{}');
  } catch {
    console.error('[lead] Could not parse tool arguments.');
    return failText;
  }

  // Ask for the thing that is actually missing, so the visitor is never sent
  // looking for something they already gave.
  // Second, independent check on agreement: the model says the visitor confirmed,
  // and the visitor's own words have to bear that out. Both must agree to send.
  if (args.confirmed === true && !visitorAgreed(message)) {
    console.warn('[lead] Model claimed confirmation the visitor did not give.');
    args.confirmed = false;
  }

  const check = validateLead(args);
  if (!check.ok) {
    console.warn(`[lead] Rejected: ${check.reason}`);
    switch (check.reason) {
      case 'not confirmed':
        return `Just to check before I send it to ${owner}: shall I pass that on as it stands?`;
      case 'invalid contact':
        return `That contact detail does not look quite right, so I have not sent anything yet. Could you give me an email address, phone number, or LinkedIn profile I can pass on?`;
      case 'reason too short':
        return `What should I tell ${owner} you are getting in touch about?`;
      default:
        return `I need a way for ${owner} to reach you before I send this. An email address, phone number, or LinkedIn profile all work.`;
    }
  }

  if (guardSendRate(ip)) {
    return `I have already passed on a few messages from here recently. For anything further, please reach ${owner} directly using the contact buttons below.`;
  }

  const sent = await sendOwnerEmail(check.lead, env, config);
  if (!sent) return failText;

  return buildSentConfirmation(check.lead, owner);
}

// Tells the visitor exactly what left the building: which contact details were
// passed on and what the enquiry said. Written by the worker from the data that
// was actually sent, so the summary can never describe something different from
// the email itself.
function buildSentConfirmation(lead, owner) {
  const routes = [lead.email, lead.phone, lead.linkedin].filter(Boolean).join(' and ');

  // The enquiry is quoted back short: enough for the visitor to spot a mistake
  // without repeating a long message back at them.
  const MAX_QUOTED = 140;
  const quoted = lead.reason.length > MAX_QUOTED
    ? lead.reason.slice(0, MAX_QUOTED).trim() + '...'
    : lead.reason;

  const closing = lead.email
    ? `${owner} will reply to ${lead.email} directly.`
    : `${owner} will get back to you on that.`;

  return `Sent to ${owner}. I passed on your contact details (${routes}) and this: "${quoted}" ${closing} If it is urgent, the calendar link below is the fastest route.`;
}

function trimHistory(history, config) {
  const turns = config.historyTurns ?? 4;
  return history.slice(-(turns * 2));
}

function detectLeadIntent(message) {
  return LEAD_INTENT_KEYWORDS.some(kw => message.toLowerCase().includes(kw));
}

// True when the assistant's own reply refers the visitor to a contact route,
// so the contact buttons it mentions are actually rendered. Covers the standard
// "contact buttons below" / "reach ... directly" phrasing and any reply that
// prints a real contact address or link (email, calendar, LinkedIn).
function replyRefersToContact(reply, contactMethods) {
  if (typeof reply !== 'string') return false;
  const r = reply.toLowerCase();
  if (r.includes('contact button')) return true;
  if (/\b(reach|contact|get in touch|reach out|book a call)\b/.test(r) &&
      /\b(direct|below|gil|calendly|linkedin|email)\b/.test(r)) return true;
  for (const v of [contactMethods?.email, contactMethods?.calendar, contactMethods?.linkedin]) {
    if (v && r.includes(String(v).toLowerCase())) return true;
  }
  return false;
}

function buildCTAs(contactMethods) {
  if (!contactMethods) return [];
  const ctas = [];
  if (contactMethods.email)    ctas.push({ type: 'email',    label: 'Email',        href: `mailto:${contactMethods.email}` });
  if (contactMethods.linkedin) ctas.push({ type: 'linkedin', label: 'LinkedIn',     href: contactMethods.linkedin });
  if (contactMethods.whatsapp) ctas.push({ type: 'whatsapp', label: 'WhatsApp',     href: `https://wa.me/${contactMethods.whatsapp.replace(/\D/g, '')}` });
  if (contactMethods.sms)      ctas.push({ type: 'sms',      label: 'SMS',          href: `sms:${contactMethods.sms}` });
  if (contactMethods.calendar) ctas.push({ type: 'calendar', label: 'Book a call',  href: contactMethods.calendar });
  if (contactMethods.github)   ctas.push({ type: 'github',   label: 'GitHub',       href: contactMethods.github });
  for (const c of (contactMethods.custom ?? [])) {
    if (c.label && c.href) ctas.push({ type: 'custom', label: c.label, href: c.href });
  }
  return ctas;
}

// Routes to the correct LLM provider based on config.llm.provider.
// Supported: 'openai' (default), 'anthropic'.
// Set LLM_API_KEY as a Cloudflare secret (npx wrangler secret put LLM_API_KEY).
// Both callers return the same shape: { text, toolCall }. toolCall is null unless
// the model asked to send a message, which only the OpenAI path currently offers.
async function callLLM(systemPrompt, history, message, env, config) {
  // Local development without an API key: set LLM_MOCK=1 in worker/.dev.vars.
  // Never set in production; the reply makes clear it is a stand-in.
  if (env.LLM_MOCK) return mockLLM(systemPrompt, history, message);

  const provider = config.llm?.provider ?? 'openai';
  if (provider === 'anthropic') {
    return callAnthropic(systemPrompt, history, message, env, config);
  }
  return callOpenAI(systemPrompt, history, message, env, config);
}

// Stand-in for the model during local development. Echoes enough of the
// request to prove the plumbing (prompt size, history length, session line)
// without any network call.
function mockLLM(systemPrompt, history, message) {
  const status = /SESSION STATUS\n(.*)/.exec(systemPrompt)?.[1] ?? '';
  const text =
    `(Stand-in model, no API key locally.) You asked: "${message}". ` +
    `I was given ${systemPrompt.length} characters of instructions and ${history.length} earlier messages. ` +
    (status ? `${status.split('.')[0]}.` : '');
  return Promise.resolve({ text, toolCall: null });
}

// OpenAI Chat Completions API.
// Default model: gpt-4o-mini (cheap, fast, good quality for this use case).
// Override via llm.model in bot.config.json (e.g. "gpt-4o", "gpt-4-turbo").
async function callOpenAI(systemPrompt, history, message, env, config) {
  const maxTokens = Math.ceil((config.maxAnswerWords ?? 80) * 1.5) + 50;
  const model     = config.llm?.model ?? 'gpt-4o-mini';
  const messages  = [
    { role: 'system', content: systemPrompt },
    ...history,
    { role: 'user',   content: message },
  ];

  const body = { model, messages, max_tokens: maxTokens, temperature: 0.4 };
  if (config.leadCapture?.enabled) body.tools = [LEAD_TOOL];

  const response = await fetch('https://api.openai.com/v1/chat/completions', {
    method: 'POST',
    headers: {
      'Content-Type':  'application/json',
      'Authorization': `Bearer ${env.LLM_API_KEY}`,
    },
    body: JSON.stringify(body),
    signal: AbortSignal.timeout(25000),
  });

  if (!response.ok) {
    const text = await response.text();
    throw new Error(`OpenAI API error ${response.status}: ${text}`);
  }

  const data    = await response.json();
  const choice  = data.choices?.[0]?.message ?? {};
  const call    = choice.tool_calls?.find(c => c.function?.name === LEAD_TOOL.function.name);

  return {
    text:     choice.content ?? '',
    toolCall: call ? { arguments: call.function.arguments } : null,
  };
}

// Anthropic Messages API.
// Default model: claude-haiku-4-5-20251001 (cheap, fast).
// Override via llm.model in bot.config.json (e.g. "claude-sonnet-4-6").
// Note: Anthropic uses a separate 'system' field instead of a system message in the array.
async function callAnthropic(systemPrompt, history, message, env, config) {
  const maxTokens = Math.ceil((config.maxAnswerWords ?? 80) * 1.5) + 50;
  const model     = config.llm?.model ?? 'claude-haiku-4-5-20251001';
  const messages  = [...history, { role: 'user', content: message }];

  const response = await fetch('https://api.anthropic.com/v1/messages', {
    method: 'POST',
    headers: {
      'Content-Type':      'application/json',
      'x-api-key':         env.LLM_API_KEY,
      'anthropic-version': '2023-06-01',
    },
    body: JSON.stringify({ model, system: systemPrompt, messages, max_tokens: maxTokens }),
    signal: AbortSignal.timeout(25000),
  });

  if (!response.ok) {
    const text = await response.text();
    throw new Error(`Anthropic API error ${response.status}: ${text}`);
  }

  const data = await response.json();
  return { text: data.content?.[0]?.text ?? '', toolCall: null };
}

function buildResponse(body, status, request, config) {
  const allowedOrigins = config?.security?.allowedOrigins ?? [];
  const origin         = request?.headers?.get('Origin') ?? '';
  const originAllowed  = !allowedOrigins.length || allowedOrigins.includes(origin);

  const headers = {
    'Content-Type':               'application/json',
    'Access-Control-Allow-Methods': 'POST, GET, OPTIONS',
    'Access-Control-Allow-Headers': 'Content-Type, X-Widget-Token, Authorization',
    'X-Content-Type-Options':     'nosniff',
  };

  // Only set Access-Control-Allow-Origin when the origin is permitted.
  // Omitting it for blocked origins prevents the browser from reading
  // the cross-origin response body, even on 4xx error replies.
  if (originAllowed && origin) {
    headers['Access-Control-Allow-Origin'] = origin;
  }

  if (status === 204 || body === null) {
    return new Response(null, { status, headers });
  }
  return new Response(JSON.stringify(body), { status, headers });
}
